### ISSUE TITLE
When backend is down while connector starts, it crashes.

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/connector#18]
While creating a docker compose stack, i discovered that the connector crashes when its started before the backend.
This should be catched & handeld by the "try" mechanism.

Dosnt matter if the backend is ready or not, connector should start and keep trying to connect.

**Comment by mStirner** [comment]
```
backend    | [2022.12.06 - 18:15.42.420][info][system] Connected to "mongodb://database:27017/OpenHaus"
connector  | Backend http://backend:8080 not reachable, re try attempt 1...
connector  | node:events:491
connector  |       throw er; // Unhandled 'error' event
connector  |       ^
connector  | 
connector  | Error: connect ECONNREFUSED 172.23.0.3:8080
connector  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
connector  | Emitted 'error' event on WebSocket instance at:
connector  |     at emitErrorAndClose (/opt/OpenHaus/connector/node_modules/ws/lib/websocket.js:984:13)
connector  |     at ClientRequest.<anonymous> (/opt/OpenHaus/connector/node_modules/ws/lib/websocket.js:841:5)
connector  |     at ClientRequest.emit (node:events:513:28)
connector  |     at Socket.socketErrorListener (node:_http_client:494:9)
connector  |     at Socket.emit (node:events:513:28)
connector  |     at emitErrorNT (node:internal/streams/destroy:157:8)
connector  |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
connector  |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
connector  |   errno: -111,
connector  |   code: 'ECONNREFUSED',
connector  |   syscall: 'connect',
connector  |   address: '172.23.0.3',
connector  |   port: 8080
connector  | }
```
