### ISSUE TITLE
`Error in worker "ssdp.js" Error: Text data outside of root node.`

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/connector#37]
```
[2024.01.10 - 21:33.30.700][error][forwarder] Error in worker "ssdp.js" Error: Text data outside of root node.
Line: 1
Column: 15
Char: t
    at error (/home/marc/projects/OpenHaus/!connector/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/home/marc/projects/OpenHaus/!connector/node_modules/sax/lib/sax.js:677:7)
    at SAXParser.write (/home/marc/projects/OpenHaus/!connector/node_modules/sax/lib/sax.js:1035:15)
    at module.exports (/home/marc/projects/OpenHaus/!connector/node_modules/xml-js/lib/xml2js.js:346:12)
    at module.exports (/home/marc/projects/OpenHaus/!connector/node_modules/xml-js/lib/xml2json.js:13:8)
    at /home/marc/projects/OpenHaus/!connector/ssdp.js:88:28
    at /home/marc/projects/OpenHaus/!connector/request.js:108:17
    at IncomingMessage.<anonymous> (/home/marc/projects/OpenHaus/!connector/request.js:40:13)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1589:12) {
  note: Error: Text data outside of root node.
  Line: 1
  Column: 15
  Char: t
      at error (/home/marc/projects/OpenHaus/!connector/node_modules/sax/lib/sax.js:651:10)
      at strictFail (/home/marc/projects/OpenHaus/!connector/node_modules/sax/lib/sax.js:677:7)
      at SAXParser.write (/home/marc/projects/OpenHaus/!connector/node_modules/sax/lib/sax.js:1035:15)
      at module.exports (/home/marc/projects/OpenHaus/!connector/node_modules/xml-js/lib/xml2js.js:346:12)
      at module.exports (/home/marc/projects/OpenHaus/!connector/node_modules/xml-js/lib/xml2json.js:13:8)
      at /home/marc/projects/OpenHaus/!connector/ssdp.js:88:28
      at /home/marc/projects/OpenHaus/!connector/request.js:108:17
      at IncomingMessage.<anonymous> (/home/marc/projects/OpenHaus/!connector/request.js:40:13)
      at IncomingMessage.emit (node:events:526:35)
      at endReadableNT (node:internal/streams/readable:1589:12)
}
```

**Comment by mStirner** [comment]
Just noticed that it seems like the wrong connector. Why is the connector folder prefixed with `!`??
